// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALJxCZ4GuRzB5W6p-PY9_jLZ4Zl_bP5uo',
    appId: '1:658467762037:web:09e3838445bccc958b2d3c',
    messagingSenderId: '658467762037',
    projectId: 'my-gpt-gemini',
    authDomain: 'my-gpt-gemini.firebaseapp.com',
    storageBucket: 'my-gpt-gemini.appspot.com',
    measurementId: 'G-NT54YTG7F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCygPDUXOl3fuOBugsmTsGk9ns3OBafyyA',
    appId: '1:658467762037:android:627d123788905f538b2d3c',
    messagingSenderId: '658467762037',
    projectId: 'my-gpt-gemini',
    storageBucket: 'my-gpt-gemini.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOUeudt1UxnJ2HHZvQOQ6GwL_hIfN88X8',
    appId: '1:658467762037:ios:8c9ae8a9d5e82d168b2d3c',
    messagingSenderId: '658467762037',
    projectId: 'my-gpt-gemini',
    storageBucket: 'my-gpt-gemini.appspot.com',
    iosBundleId: 'com.example.mygpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOUeudt1UxnJ2HHZvQOQ6GwL_hIfN88X8',
    appId: '1:658467762037:ios:d05bbc633409fad28b2d3c',
    messagingSenderId: '658467762037',
    projectId: 'my-gpt-gemini',
    storageBucket: 'my-gpt-gemini.appspot.com',
    iosBundleId: 'com.example.mygpt.RunnerTests',
  );
}
